overcount: overcount.cpp
	g++ overcount.cpp -o ../overcount -std=c++11 \
    -I/home/altman.ro/opt/include/mongocxx/v_noabi \
    -I/home/altman.ro/opt/include/bsoncxx/v_noabi \
    -L/home/altman.ro/opt/lib -lmongocxx -lbsoncxx -lcppalp