#!/bin/bash

#Install Mathematica
if [ "$($(which math | rev | cut -d'/' -f1 --complement | rev)/../monitorlm 2>&1)" != "Could not find a MathLM server." ]
then
    initfile=$(math -noprompt -run "WriteString[\$Output,\$UserBaseDirectory<>\"/Kernel/init.m\"];Exit[];" 2>/dev/null)
    echo $(cat ${initfile} | grep -v "CRUNCH_ROOT") > $initfile
    echo "AppendTo[\$Path, Environment[\"CRUNCH_ROOT\"]<>\"/packages/Mathematica/cohomCalg\"]" >> ${initfile}
    echo "AppendTo[\$Path, Environment[\"CRUNCH_ROOT\"]<>\"/packages/Mathematica/MongoLink\"]" >> ${initfile}
fi