#!/bin/bash

mainpath="/gss_gpfs_scratch/altman.ro"
herepath="${mainpath}/modules/triangulatecones/template"
toriccypath="${mainpath}/ToricCY/packages/python/toriccy"

djob 2>/dev/null
djob 2>/dev/null
rm ${herepath}/*.err ${herepath}/*.out 2>/dev/null
rm -r ${herepath}/jobs/* 2>/dev/null
rm ${herepath}/querystate* 2>/dev/null
echo "jobstep,exitcode,resubmitq" > ${herepath}/skippedstate 2>/dev/null
echo -e "batchcounter,stepcounter\n1,1" > ${herepath}/counterstate 2>/dev/null
echo "Pending" > ${herepath}/statusstate 2>/dev/null
currdir=$(pwd)
cd ${toriccypath}
python setup.py install --user --record filespy.txt
sage --python setup.py install --user --record filessage.txt
cd ${curdir}
