#!/bin/bash

installpath="$(cd $(dirname ${BASH_SOURCE[0]}) && pwd -P)"

# Source DBCrunch modules for Discovery

echo "Sourcing DBCrunch modules for Discovery..."

if [ ! -f ${HOME}/.bashrc ]
then
    touch ${HOME}/.bashrc
fi

if ! grep -q "# Source DBCrunch modules for Discovery" ${HOME}/.bashrc
then
    echo "" >> ${HOME}/.bashrc
    echo "# Source DBCrunch modules for Discovery" >> ${HOME}/.bashrc
    echo "" >> ${HOME}/.bashrc
    echo "if [ -f $(echo ${installpath}/env/discovery_modules_env | sed 's|'"${CRUNCH_ROOT}"'|${CRUNCH_ROOT}|g' | sed 's|'"${HOME}"'|${HOME}|g' | sed 's|'"${USER}"'|${USER}|g') ]" >> ${HOME}/.bashrc
    echo "then" >> ${HOME}/.bashrc
    echo "    . $(echo ${installpath}/env/discovery_modules_env | sed 's|'"${CRUNCH_ROOT}"'|${CRUNCH_ROOT}|g' | sed 's|'"${HOME}"'|${HOME}|g' | sed 's|'"${USER}"'|${USER}|g')" >> ${HOME}/.bashrc
    echo "fi" >> ${HOME}/.bashrc
fi

if ! grep -q "# Source Sage environment variables" ${HOME}/.bashrc
then
    echo "" >> ${HOME}/.bashrc
    echo "# Source Sage environment variables" >> ${HOME}/.bashrc
    echo "" >> ${HOME}/.bashrc
    echo "if [ -f $(echo ${installpath}/env/sage_env | sed 's|'"${CRUNCH_ROOT}"'|${CRUNCH_ROOT}|g' | sed 's|'"${HOME}"'|${HOME}|g' | sed 's|'"${USER}"'|${USER}|g') ]" >> ${HOME}/.bashrc
    echo "then" >> ${HOME}/.bashrc
    echo "    . $(echo ${installpath}/env/sage_env | sed 's|'"${CRUNCH_ROOT}"'|${CRUNCH_ROOT}|g' | sed 's|'"${HOME}"'|${HOME}|g' | sed 's|'"${USER}"'|${USER}|g')" >> ${HOME}/.bashrc
    echo "fi" >> ${HOME}/.bashrc
fi

. ${HOME}/.bashrc

# Move Mathematica license scripts to ${USER_LOCAL}

echo "Moving Mathematica license scripts to \${USER_LOCAL}..."

cp ${installpath}/bin/mathematica_* ${USER_LOCAL}/bin/